### ISSUE TITLE
Example gbl_dut not working

### ISSUE THREAD

**Issue by maweer** [eutelescope/eutelescope#378] opened 2018-04-13 14:16 UTC
The example gbl_dut is not working at the moment, because only the aligngbl-temp is provided in the steering-templates.
Could you add the other templates which are needed and commend in which order they have to be started?

Thank you.

**Comment by dreyling** [comment] 2018-05-07 10:44
@tbisanz can you remind me, where exactly the problem is? You said something like hard coded plane IDs, if I remember correctly.

**Comment by edorossi** [comment] 2019-01-21 13:21
GBL_DUT has been updated and it is part of #447. It will be merged very soon. I close the issue since it is related to an obsolete version of the example.

**Closed by edorossi** 2019-01-21 13:21 UTC
