### ISSUE TITLE
Covariance Matrix of a hit not transformed when going from local <--> global

### ISSUE THREAD

**Issue by tbisanz** [eutelescope/eutelescope#156] opened 2014-11-24 17:29 UTC

**Comment by edorossi** [comment] 2019-01-25 22:34
If I am not wrong, the covariance matrix of hits is used only for track fitting and alignment. In both cases, we are actually providing these values as an input to the source code (from the config file), and not retrieving the value from the LCIO. This is at least the case for GBL and DAF.
Perhaps I am missing some situations where this can be useful for how the code is currently written, but I close the issue since it is not probably the case.

**Closed by edorossi** 2019-01-25 22:34 UTC
Labels: Question

**Comment by TCThenna** [comment] 2019-01-28 08:43
I have to think about this one a little bit more. 
In principle, the user knows the cov in the local system. Now, if you transform into the global system, e.g. a small rotation, in principal the uncertainty along local x is not the same as global x. 

In the current GBL implementation, this is not implemented, but we think that this is negligible. In principle, the approach to set local cov and let the code do the rest is of course nice.

**Comment by edorossi** [comment] 2019-01-28 09:04
Hi @TCThenna ,
I totally see your point, but I closed the issue since it is outdated by now, since the problem is not only that the covariance matrices do not rotate, but that they are not used at all. We could have a discussion about implementing them in the future, but in that case we can just open a fresh issue with a new description of what the status is.
