### ISSUE TITLE
Replace your GLB-fitter processors with the "common" EUTelGBLFitter

### ISSUE THREAD

**Issue by dreyling** [eutelescope/eutelescope#380] opened 2018-05-07 10:12 UTC
The goal is to merge different GLB implementations.

Thus, we ask to test this **processor for track fitting**
https://github.com/eutelescope/eutelescope/blob/master/processors/src/EUTelGBLFitter.cc
and to post here the problems and outcomes.

If you determine a missing functionality or a missing parameter, please post it here as well.

For updating the documentation on this processor (e.g. possible parameters), please use this README.md file:
https://github.com/eutelescope/eutelescope/blob/master/processors/README.md

**Comment by edorossi** [comment] 2019-01-14 15:12
EUTelAlignGBL and EUTelFitterGBL have been now merged in a single processor called EUTelGBL. I close this issue since now it is effectively a duplicate of #379

**Closed by edorossi** 2019-01-14 15:12 UTC
Labels: GBL
